version: '3.9'
services:
    ghproxy:
        image: 'moshangms/ghproxy:latest'
        restart: always
        volumes:
            - './ghproxy/log:/data/ghproxy/log'
            - './ghproxy/config:/data/ghproxy/config'
        ports:
            - '127.0.0.1:5000:8080'
